/**
 * Soil Moisture API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GeoJSONToWKBPolygon } from './geoJSONToWKBPolygon';
import { GeoJSONToWKBMultiPolygon } from './geoJSONToWKBMultiPolygon';


export interface Aoi { 
    type: Aoi.TypeEnum;
    coordinates: Array<Array<Array<Array<string>>>>;
}
export namespace Aoi {
    export type TypeEnum = 'Polygon' | 'MultiPolygon';
    export const TypeEnum = {
        Polygon: 'Polygon' as TypeEnum,
        MultiPolygon: 'MultiPolygon' as TypeEnum
    };
}


