/**
 * Soil Moisture API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GeometryCollection } from './geometryCollection';
import { MultiPoint } from './multiPoint';
import { MultiLineString } from './multiLineString';
import { LineString } from './lineString';
import { MultiPolygon } from './multiPolygon';
import { Bbox } from './bbox';
import { Point } from './point';
import { Polygon } from './polygon';
import { CoordinatesInner } from './coordinatesInner';


/**
 * @type GeometriesInner
 * @export
 */
export type GeometriesInner = GeometryCollection | LineString | MultiLineString | MultiPoint | MultiPolygon | Point | Polygon;

