/**
 * Soil Moisture API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { JobExecutionResult } from './jobExecutionResult';
import { ProductType } from './productType';


export interface JobExecutionCreated { 
    startDate: string;
    endDate: string;
    executionStartDate: string;
    id: string;
    outputPath?: string | null;
    result?: JobExecutionResult | null;
    executionEndDate?: string | null;
    userId: string;
    productType: ProductType;
    jobs: Array<string>;
    rootPath: string;
    rerun?: boolean;
    errors: Array<string>;
}
export namespace JobExecutionCreated {
}


