/**
 * Soil Moisture API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { JobExecutionResult } from './jobExecutionResult';


export interface JobExecutionUpdate { 
    executionId: string;
    jobId: string;
    result: JobExecutionResult;
    executionEndDate: string;
    additionalInformation?: string | null;
    errorId?: string | null;
    errorName?: string | null;
    files?: Array<string> | null;
}
export namespace JobExecutionUpdate {
}


