/**
 * Soil Moisture API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type JobStatus = 'INACTIVE' | 'ACTIVE' | 'QUEUED' | 'RUNNING' | 'UNPROCESSABLE';

export const JobStatus = {
    Inactive: 'INACTIVE' as JobStatus,
    Active: 'ACTIVE' as JobStatus,
    Queued: 'QUEUED' as JobStatus,
    Running: 'RUNNING' as JobStatus,
    Unprocessable: 'UNPROCESSABLE' as JobStatus
};

