/**
 * Soil Moisture API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Bbox } from './bbox';
import { CoordinatesInner } from './coordinatesInner';


/**
 * MultiLineString Model
 */
export interface MultiLineString { 
    bbox?: Bbox | null;
    type: MultiLineString.TypeEnum;
    coordinates: Array<Array<CoordinatesInner>>;
}
export namespace MultiLineString {
    export type TypeEnum = 'MultiLineString';
    export const TypeEnum = {
        MultiLineString: 'MultiLineString' as TypeEnum
    };
}


