/**
 * Soil Moisture API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Bbox } from './bbox';
import { CoordinatesInner } from './coordinatesInner';


/**
 * Polygon Model
 */
export interface Polygon { 
    bbox?: Bbox | null;
    type: Polygon.TypeEnum;
    coordinates: Array<Array<CoordinatesInner>>;
}
export namespace Polygon {
    export type TypeEnum = 'Polygon';
    export const TypeEnum = {
        Polygon: 'Polygon' as TypeEnum
    };
}


