/**
 * Soil Moisture API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type Priority = 'very_low' | 'low' | 'normal' | 'high' | 'very_high';

export const Priority = {
    VeryLow: 'very_low' as Priority,
    Low: 'low' as Priority,
    Normal: 'normal' as Priority,
    High: 'high' as Priority,
    VeryHigh: 'very_high' as Priority
};

