/**
 * Soil Moisture API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type ProductType = 'SM100m' | 'SM1km' | 'BIOMASS' | 'WHC';

export const ProductType = {
    Sm100m: 'SM100m' as ProductType,
    Sm1km: 'SM1km' as ProductType,
    Biomass: 'BIOMASS' as ProductType,
    Whc: 'WHC' as ProductType
};

